name: Build LaTeX document and git diff
on: [push]
         
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          root_file: master.tex
                   
      - name: latex-diff
        uses: tawalaya/latex-diff-action@v1
        with:
          root_file: master.tex
          compile_diff: true
          
      - name: Upload as artifact
        uses: actions/upload-artifact@master
        with:
          name: diff.pdf
          path: .
        if: always()          
