name: Build LaTeX document and git diff
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: master.tex
      - uses: tawalaya/latex-diff-action@v1
        with:
          root_file: master.tex
          compile_diff: true
      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: diff.pdf
          path: .
        if: always()          
